### ISSUE TITLE
fofa

### ISSUE THREAD

**Issue by jiecoke** [piaolin/fofa2Xray#14]
fofa域名更改成fofa.info，能更改下嘛
![image](https://user-images.githubusercontent.com/39594997/179167890-d4f3a54b-eb1c-470b-8cc7-69ab2999e6f8.png)

**Comment by Yvesssn** [comment]
已更改。

**Comment by jiecoke** [comment]
阿里嘎多！！！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "piaolin/fofa2Xray"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月16日(星期六) 凌晨0:19
***@***.***&gt;;
抄送:&nbsp;"✎ℳ๓ ***@***.******@***.***&gt;;
主题:&nbsp;Re: [piaolin/fofa2Xray] fofa (Issue #14)





 
已更改。
