### ISSUE TITLE
请教师傅一下，师傅这个是什么情况，fofa的key账号之类的我也是正常配置了

### ISSUE THREAD

**Issue by SuPejkj** [piaolin/fofa2Xray#4]
![image](https://user-images.githubusercontent.com/46962826/89123563-f416b080-d502-11ea-9f34-194dc9543d20.png)

**Comment by Yvesssn** [comment]
账号与key无需放在“{}”中。

**Comment by SuPejkj** [comment]
![image](https://user-images.githubusercontent.com/46962826/89124097-e06d4900-d506-11ea-9fdb-fef4fc808199.png)
秘钥跟账号我没放在{}里0.0

**Comment by Yvesssn** [comment]
可以试一下手动调用api判断key与账号是否正确，具体调用方法可以参考http://fofa.so/static_pages/api_help，另外fofa注册用户（非普通用户）是没有免费查询额度的。
