### ISSUE TITLE
fofa语句需使用双引号该如何添加？

### ISSUE THREAD

**Issue by A-dmins** [piaolin/fofa2Xray#8]
有时候fofa语句需要使用app="xxx"时，在运行程序时，程序会直接去掉双引号导致查询结果不准确，还有就是查询的结果数量能进行修改吗？fofa的高级会员比普通会员的查询结果数量要多，能全部添加到队列里么？

**Comment by Yvesssn** [comment]
已收到，会在后续进行更新。
